package com.Timbua.backend.config;

import com.Timbua.backend.model.MaterialSite;
import com.Timbua.backend.service.MaterialSiteService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

@Component
public class MaterialSiteDataLoader implements CommandLineRunner {

    @Autowired
    private MaterialSiteService materialSiteService;

    @Override
    public void run(String... args) throws Exception {
        // Check if data already exists to avoid duplicates
        if (materialSiteService.getAllMaterialSites().isEmpty()) {
            // Load all records from all locations
            List<MaterialSite> initialSites = Arrays.asList(
                    // ========== KISAUNI DATA (Rows 1-34) ==========
                    new MaterialSite(1, "001B", "Sand", "Junda-Kilalapo kwa kishanga",
                            new BigDecimal("-4.01597"), new BigDecimal("39.672954"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Foundations, walling, paving",
                            "21-50 men. 1-10 women", "Ngomeni, Bengala, Timboni", "1-10 tonnes", null),
                    new MaterialSite(2, "001B", "Bricks", "Junda- Misleni",
                            new BigDecimal("-4.010551"), new BigDecimal("39.672492"), "in the county",
                            "Small industry", "1 year", "Individual", "Walling",
                            "1-10 men", "Kanjiweni", "400 tons", null),
                    new MaterialSite(3, "001B", "Ventilation blocks", "Junda- Misleni",
                            new BigDecimal("-4.010551"), new BigDecimal("39.672492"), "in the county",
                            "Small industry", "2 year", "Individual", "Decoration , interior design",
                            "1-10 men", null, "1-10 units", null),
                    new MaterialSite(4, "001B", "Limestone", "Junda_Kilalapo kwa kishanga",
                            new BigDecimal("-4.0145971"), new BigDecimal("39.672954"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Foundations",
                            "21-50 men", null, "1-10 units", null),
                    new MaterialSite(5, "001B", "Tmber/wood", "Mwakurunge- Usederi",
                            new BigDecimal("-3.9842"), new BigDecimal("39.693988"), "in the county",
                            "Small industry", "1 year", "Individual", "Roofing, interior design",
                            "1-10 men", null, "100 - 500 units", "The timber is used for doors and roofing"),
                    new MaterialSite(6, "001B", "Blocks", "Mwakurunge- Ngutatu",
                            new BigDecimal("-3.989252"), new BigDecimal("39.68099"), "in the county",
                            "Small industry", "2 year", "Individual", "Foundations, walling , roofing",
                            "1-10 men", null, "100 - 500 units", "There are several men producing similar blocks in the area"),
                    new MaterialSite(7, "001B", "Stones that make cement", "Mwakurunge- Ugatunzi(Kiembeni)",
                            new BigDecimal("-3.984019"), new BigDecimal("39.693979"), "in the county",
                            "Large industry, quarrying", "10-19 years", "Shale quarry(private company)", "Foundaations, walling , paving, decoration, interior design , flooring",
                            "1-10 men", null, "500-1000 units", "The product is transported to bamburi cement for manufacture of cement"),
                    new MaterialSite(8, "001B", "Makuti", "Bamburi_wema",
                            new BigDecimal("-3.992309"), new BigDecimal("39.7048115"), "in the county",
                            "Smal industry", "5-9 years", "Kijiji farm(individual)", "Roofing",
                            "1-10 men", "Around Wema", "150-500", "Many individuals make makuti"),
                    new MaterialSite(9, "001B", "Ventilation blocks", "Bamburi-Balawa",
                            new BigDecimal("-3.9833"), new BigDecimal("39.714746"), "in the county",
                            "Smal industry", "5-9 years", "Individual", "Decoration , interior design",
                            "1-10 men", null, "500 - 1000 units", null),
                    new MaterialSite(10, "001B", "Concrete(used to make cemet)", "Bamburi- Timbo(Kashani)",
                            new BigDecimal("-3.967072"), new BigDecimal("39.708678"), "in the county",
                            "Quarrying", "5-9 years", "Individual", "Foundation, Paving, Flooring",
                            "1-10 men", "Zimlati", "501 - 1000 tonnes", "Machines do most of the work, Many places that provide concrete are around Kashana area"),
                    new MaterialSite(11, "001B", "Sand", "Bamburi_ Kashani",
                            new BigDecimal("-3.967072"), new BigDecimal("39.708678"), "in the county",
                            "Quarrying", "5-9 years", "Individual", "Foundation, walling, paving, interior design, maintenance, flooring",
                            "1-10 men", "Around kashani area, Zimlati", "502 - 1000 tonnes", "Machines do most of the work, Many places that provide concrete are around Kashana area"),
                    new MaterialSite(12, "001B", "Bulding stones", "Bamburi_ Kashani",
                            new BigDecimal("-3.967072"), new BigDecimal("39.708678"), "in the county",
                            "Quarrying", "5-9 years", "Individual", "Foundations, walling, paving, flooring",
                            "1-10 men", "Around kashani area, Zimlati", "500-1000 tonnes", "Machines aree used to extract"),
                    new MaterialSite(13, "001B", "Coral reef stones", "Shanzu-Maweni",
                            new BigDecimal("-3.9779"), new BigDecimal("39.729153"), "in the county",
                            "Small industry, quarrying", "10-19 years", "Community", "Walling , paving",
                            "51-100 men", null, "500-1000 tonnes", "Area is owned by community"),
                    new MaterialSite(14, "001B", "Blocks", "Shanzu-Maweni",
                            new BigDecimal("-3.9779"), new BigDecimal("39.729153"), "in the county",
                            "Small industry", "10-19 years", "Community", "Foundations, walling , paving",
                            "51-100 men", null, "500-1000 tonnes", "Area is owned by community"),
                    new MaterialSite(15, "001B", "Sand", "Shanzu-Maweni",
                            new BigDecimal("-3.9779"), new BigDecimal("39.729153"), "in the county",
                            "Small industry", "10-19 years", "Community", "Foundations, walling , paving, maintenance, flooring",
                            "51-100 men", null, "500-1000 tonnes", "Area is owned by community"),
                    new MaterialSite(16, "001B", "Metal Windows and doors", "Mwakurunge-Ugatunzi kiembeni",
                            new BigDecimal("-3.984019"), new BigDecimal("39.6939"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Walling, roofing",
                            "1-10 men", null, "150-500 units", "Workshop makes windows and doors"),
                    new MaterialSite(17, "001B", "Chips blocks", "Bamburi-Balawa",
                            new BigDecimal("-3.9833"), new BigDecimal("39.714746"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Decoration, interior design",
                            "1-10 men", null, "150-500 units", null),
                    new MaterialSite(18, "001B", "Balcony balustrades", "Bamburi-Balawa",
                            new BigDecimal("-3.9833"), new BigDecimal("39.714746"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Decoration, interior design",
                            "1-10 men", null, "150-500 units", "The individuals produce it themselves"),
                    new MaterialSite(19, "001B", "Ventilation blocks", "Mtopanga-Siowatu",
                            new BigDecimal("-4.014474"), new BigDecimal("39.693133"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Decoration, interior design",
                            "1-10 men", null, "150-500 units", null),
                    new MaterialSite(20, "001B", "Glass", "Bamburi- Bamburi mwisho",
                            new BigDecimal("-4.002331"), new BigDecimal("39.700027"), "in the county",
                            "Small industry", "1 year", "Mozain glass hardware and electrical", "Walling, interior design",
                            "1-10 men", null, "1-10 units", "Glass used in making windows and doors"),
                    new MaterialSite(21, "001B", "Culvert", "Mtopanga-Siowatu",
                            new BigDecimal("-4.014474"), new BigDecimal("39.693133"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Decoration, interior design",
                            "1-10 men", null, "150-500 units", null),
                    new MaterialSite(22, "001B", "Poles", "Mtopanga-Siowatu",
                            new BigDecimal("-4.014474"), new BigDecimal("39.693133"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Walling, roofing, decoration, interior design",
                            "1-10 men", null, "150-500 units", "The individuals produce it themselves"),
                    new MaterialSite(23, "001B", "Balusters", "Mtopanga-Siowatu",
                            new BigDecimal("-4.014474"), new BigDecimal("39.693133"), "in the county",
                            "Small industry", "5-9 years", "Individual", "Walling, roofing, decoration, interior design",
                            "1-10 men", null, "150-500 units", "The individuals produce it themselves"),
                    new MaterialSite(24, "001B", "Metal Windows and doors", "Mtopanga-stage ya paka",
                            new BigDecimal("-4.028393"), new BigDecimal("39.677455"), "in the county",
                            "Small industry", "5-9 years", "Katungauliah General Works", "Roofing, interior design",
                            "1-10 men", "Jacarand, within mtopanga area , a lot of people are producing", "150-500 units", "The windows , gates and doors are made from metal and wood"),
                    new MaterialSite(25, "001B", "Culvetrs", "Bamburi-Mwembeni",
                            new BigDecimal("-4.005788"), new BigDecimal("39.697018"), "in the county",
                            "Small industry", "1 year", "Sirago building contractors LTD", "Roads",
                            "1-10 men", "Around Bamburi area, Around Vescom", "500-1000 units", "This is a branch of Siargo Building contractors LTD"),
                    new MaterialSite(26, "001B", "Concrete", "Bamburi-Mwembeni",
                            new BigDecimal("-4.005788"), new BigDecimal("39.697018"), "in the county",
                            "Small industry", "1 year", "Sirago building contractors LTD", "Roofing, roads, interoir design",
                            "1-10 men", "Around Bamburi area, Around Vescom", "500-1000 units", "This is a branch of Siargo Building contractors LTD"),
                    new MaterialSite(27, "001B", "Road caps", "Bamburi-Mwembeni",
                            new BigDecimal("-4.005788"), new BigDecimal("39.697018"), "in the county",
                            "Small industry", "1 year", "Sirago building contractors LTD", "Decoration, roads, interoir design",
                            "1-10 men", "Around Bamburi area, Around Vescom, Bamburi cement", "500-1000 units", "This is a branch of Siargo Building contractors LTD"),
                    new MaterialSite(28, "001B", "Cinder blocks", "Bamburi-Mwembeni",
                            new BigDecimal("-4.005788"), new BigDecimal("39.697018"), "in the county",
                            "Small industry", "1 year", "Sirago building contractors LTD", "Foundation, walling, paving",
                            "1-10 men", "Around Bamburi area, Around Vescom, Bamburi cement", "500-1000 units", "This is a branch of Siargo Building contractors LTD"),
                    new MaterialSite(29, "001B", "Cement sinks", "Bamburi-Mwembeni",
                            new BigDecimal("-4.005788"), new BigDecimal("39.697018"), "in the county",
                            "Small industry", "1 year", "Sirago building contractors LTD", "Decoration,interior design, sinks",
                            "1-10 men", "Around Bamburi area, Around Vescom, Bamburi cement", "500-1000 units", "This is a branch of Siargo Building contractors LTD, sinks are used in hospitals mostly"),
                    new MaterialSite(30, "001B", "Cement", "Bamburi-Bamburi",
                            new BigDecimal("-4.004572"), new BigDecimal("39.71747"), "in the county, other counties, exported",
                            "Large industry", "20-49 years", "Bamburi  Cement factories", "Cement",
                            "Over 100 men. Over 100 women", null, "500-1000 bags", "It is the main product"),
                    new MaterialSite(31, "001B", "Poles", "Bamburi-Bamburi",
                            new BigDecimal("-4.004572"), new BigDecimal("39.71747"), "in the county, other counties, exported",
                            "Large industry", "20-49 years", "Bamburi  Cement factories", "Foundations, walling",
                            "Over 100 men. Over 100 women", "Mwembeni,around Bamburi", "500-1000 bags", "Company is privately owned"),
                    new MaterialSite(32, "001B", "Sand/coral reefs", "Shanzu-Shanzu",
                            new BigDecimal("-3.977113"), new BigDecimal("39.741586"), "Other counties",
                            "Large industry, quarrying", "10-19 years", "Bamburi cement quarry", "Foundation, roofing, paving, flooring",
                            "Over 100 men.", null, "500-1000 bags", "The land belongs to bamburi cement factory and is running out of sand"),
                    new MaterialSite(33, "001B", "Cabro", "Bamburi-Bamburi",
                            new BigDecimal("-4.004572"), new BigDecimal("39.71747"), "in the county, other counties, exported",
                            "Large industry", "10-19 years", "Bamburi cement factory", "Roofing, Decoration, interoir design",
                            "Over 100 men. Over 100 women", null, "500-1000 bags", null),
                    new MaterialSite(34, "001B", "Verntilation", "Shanzu-shanzu",
                            new BigDecimal("-3.977113"), new BigDecimal("39.741586"), "In the county",
                            "small industry", "5-9 years", "Individual", "Decoration, interior design",
                            "1-10 men", "Around shanzu", "150-500 units", null),

                    // ========== MVITA DATA (Rows 35-43) ==========
                    new MaterialSite(35, "001E", "Doors and windows", "Old town-Baghani",
                            new BigDecimal("-4.060172"), new BigDecimal("39.678511"), "In the county",
                            "Furniture", "10-19 years", "Individual", "Doors, windows and frames",
                            "1-10 men", null, "1-10 units per day", null),
                    new MaterialSite(36, "001E", "Paint", "Old town- Sogoi Kipande",
                            new BigDecimal("-4.061095"), new BigDecimal("39.670952"), "In the county",
                            "Large industries", "5-9 years", "Crown paints (Private company)", "Painting",
                            "1-10 men", null, "150-500 litres per day", null),
                    new MaterialSite(37, "001E", "Tiles", "Shimanzi_Mwembe tayari",
                            new BigDecimal("-4.06009"), new BigDecimal("39.671199"), "In the county",
                            "Small industry", "5-9 years", "Individual", "Flooring",
                            "11-20 men", null, "150-500 units", null),
                    new MaterialSite(38, "001E", "Wire mesh", "Mwembe Tayari-Mwembe tayari",
                            new BigDecimal("-4.060077"), new BigDecimal("39.671214"), "In the county",
                            "Small industry", "10-19 years", "Private company", "",
                            "1-10 men", null, "150-500 units", null),
                    new MaterialSite(39, "001E", "Riversand", "Tononoka/bondeni-Kidogobasi",
                            new BigDecimal("-4.054074"), new BigDecimal("39.669686"), "In the county",
                            "Small industry", "10-19 years", "Non Governmental", "Foundations, walling",
                            "1-10 men", null, "1-10 lorries", null),
                    new MaterialSite(40, "001E", "Doors", "Tononoka-Kiwandani",
                            new BigDecimal("-4.053411"), new BigDecimal("39.671637"), "In the county",
                            "Small industry", "20-49 years", "Kiwandani Youth Group (private company, commnity)", "Doors",
                            "11-20 men", null, "1-10 doors", null),
                    new MaterialSite(41, "001E", "Paints", "Kingorani-Railway",
                            new BigDecimal("-4.055398"), new BigDecimal("39.658629"), "In the county",
                            "Small industry", "5-9 years", "Rangi africa", "Paints",
                            "1-10 men", null, "150-500 litres", null),
                    new MaterialSite(42, "001E", "Terrazo chips", "Kingorani-Railway",
                            new BigDecimal("-4.054863"), new BigDecimal("39.658855"), "In the county",
                            "Quarrying", "Over 50 years", "Private company", "Flooring",
                            "21-50 men", null, "150-200 bags", null),
                    new MaterialSite(43, "001E", "Aluminium", "Kingorani-Railway",
                            new BigDecimal("-4.055607"), new BigDecimal("39.658534"), "In the county",
                            "Fabricating", "5-9 years", "Century aluminium renovators", "Decoration , interior design",
                            "1-10 men", null, "1-10 frames", null),

                    // ========== LIKONI DATA (Rows 44-49) ==========
                    new MaterialSite(44, "001F", "Coral stone", "Shika adabu- Maweni",
                            new BigDecimal("-4.1239081"), new BigDecimal("39.650893"), "In the county, other counties",
                            "Quarrying", "20-49 years", "Community", "Foundations, walling",
                            "25-50 men, 1-10 women", "Kwale county", "150-500 blocks", null),
                    new MaterialSite(45, "001F", "Cypress wood", "Likoni-Kona ya polisi",
                            new BigDecimal("-4.0861385"), new BigDecimal("39.6528819"), "In the county, other counties",
                            "Small industry", "10-19 years", "Private company", "Roofing",
                            "1-10 men, 1-10 women", "Kisauni sublocation", "150-500 units", null),
                    new MaterialSite(46, "001F", "Concrete", "Shika adabu- Vyemani]",
                            new BigDecimal("-4.113628"), new BigDecimal("39.637704"), "In the county",
                            "Fabricating", "5-9 years", "Inidvidual", "Paving , decoration",
                            "1-10 men", "Likoni ward, kisauni sublocation", "20-50 units", null),
                    new MaterialSite(47, "001F", "Fabric tents", "Likoni- Mkunzazini",
                            new BigDecimal("-4.107026"), new BigDecimal("39.64039"), "In the county",
                            "Small industry", "5-9 years", "Classical tent makers", "Roofing, partitioning",
                            "1-10 men, 1-10 women", "Changamwe sublocation", "1-10 units", null),
                    new MaterialSite(48, "001F", "Iron sheet", "Likoni- Mkunzazini",
                            new BigDecimal("-4.105488"), new BigDecimal("39.641448"), "In the county, other counties",
                            "Large industry", "10-19 years", "Mabati rolling mills", "Roofing, walls and partioining",
                            "11-20 men, 1-10 women", "Kilifi county", "500-1000 units", null),
                    new MaterialSite(49, "001F", "Doors and windows", "Timbwani-miami",
                            new BigDecimal("-4.0933413"), new BigDecimal("39.648775"), "In the county",
                            "Cottage industry", "5-9 years", "Friends welders", "Decoration-decorative parts and supporting materials",
                            "1-10 men, 1-10 women", "Changamwe sublocation, Kisauni sublocation", "1-10 units", null),

                    // ========== JOMVU DATA (Rows 50-58) ==========
                    new MaterialSite(50, "001C", "Steel products", "Miritini",
                            new BigDecimal("-4.001027"), new BigDecimal("39.580638"), "In the county , exported",
                            "Large industry", "20-49 year", "Dosch", "Foundation, roofing, road, interor design, flooring",
                            "Over 100 men. 1-10 women", null, "80 tons per day", "vlack pipes, SHS, RHS, CHS, Z purlins, flat bars, MS sheets"),
                    new MaterialSite(51, "001C", "Galvanized corrugated irone sheets", "Miritini",
                            new BigDecimal("-4.010623"), new BigDecimal("39.586653"), "In the county",
                            "Large industry", "Over 50 years", "Kenya general industries(private company)", "Walling, roofing",
                            "51-100 men", "Tanzania, Usonge, many developing countries", "150-500 units", null),
                    new MaterialSite(52, "001C", "Metal locking components", "Miritini",
                            new BigDecimal("-4.00813"), new BigDecimal("39.596148"), "other counties",
                            "Fabricating", "20-49 years", "Century(private company)", "Building components(locks)",
                            "21-50 men", null, "500-1000 units", "Manufactured on demand"),
                    new MaterialSite(53, "001C", "River sand", "Miritini-Mbuyu wa chapa",
                            new BigDecimal("-3.993058"), new BigDecimal("39.585388"), "In the county",
                            "Sand harvesting from river", "10-19 years", "Commuity", "Foundations, walling, flooring",
                            "21-50 men, 11-20 women", null, "7 tonnes per 2 days", "Its seasonal but beneficial."),
                    new MaterialSite(54, "001C", "Ballast", "Miritini-Mbuyu wa chapa",
                            new BigDecimal("-3.993058"), new BigDecimal("39.585388"), "In the county",
                            "Harvesting from river", "1 year", "Commuity- Mbuyu wa mchapa sand harvest communty group", "Foundations, walling, flooring- can make bricks when mixed with cement",
                            "21-50 men, 11-20 women", null, "21 tonnes per day", "Harvested as per demand"),
                    new MaterialSite(55, "001C", "Hardocore", "Jomvu-Mreroni",
                            new BigDecimal("-3.97331"), new BigDecimal("39.592047"), "In the county, other counties",
                            "Harvesting", "1 year", "Garero international(K) LTD Community Mreroni", "Foundations, walling, paving, decoration, roads, maintenace, flooring, also processed into building sand",
                            "1-10 men, 1-10 women", "Kwale county, Kilifi county", "150-500", "Special orders can be made upto 5000 tonnes, cahllenges include road infrstructure and land ownership"),
                    new MaterialSite(56, "001C", "Nails", "Jomvu--Mikindani",
                            new BigDecimal("-4.00793"), new BigDecimal("39.617417"), "In the county, other counties",
                            "Large industry", "20-49 years", "Corrugated Iron sheet LTD", "Building structrures and timber work",
                            "51-100 men", "mazeras , nairobi", "40 tonnes per day", null),
                    new MaterialSite(57, "001C", "Galvanized and colored iron sheets", "Jomvu--Mikindani",
                            new BigDecimal("-4.00793"), new BigDecimal("39.617417"), "In the county, other counties",
                            "Large industry", "20-49 years", "Corrugated Iron sheet LTD", "Walling and roofing",
                            "Over 100 men", "Mariakani, Ruiru, Nairobi", "150 tonnes per day", null),
                    new MaterialSite(58, "001C", "Reinforcement bars", "Jomvu--Mikindani-Kokotoni",
                            new BigDecimal("-4.00793"), new BigDecimal("39.617417"), "In the county, other counties",
                            "Large industry", "10-19 years", "Corrugated Iron sheet LTD", "Foundations, Roads",
                            "51-100 men", "Rabai, Mazeras , Nairobi", "100 tonnes per day", null),

                    // ========== MSAMBWENI DATA (Rows 59-69) ==========
                    new MaterialSite(59, "002/A", "Silk Sand", "Ramisi - Darigube",
                            new BigDecimal("-4.516382"), new BigDecimal("39.396835"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(60, "002/A", "Mikashorina", "Ramisi - Darigube",
                            new BigDecimal("-4.501864"), new BigDecimal("39.404864"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(61, "002/A", "River sand", "Ramisi - Turiani",
                            new BigDecimal("-4.53902"), new BigDecimal("39.385642"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(62, "002/A", "Pit Sand", "Ramisi - Voroni",
                            new BigDecimal("-4.452136"), new BigDecimal("39.46778"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(63, "002/A", "White sand, Pit sand", "Ramisi - Marigiza",
                            new BigDecimal("-4.452772"), new BigDecimal("39.458879"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(64, "002/A", "White sand, Pit sand", "Ramisi - Marigiza",
                            new BigDecimal("-4.453383"), new BigDecimal("39.458954"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(65, "002/A", "Coral stone, Ballast, Quarry dust", "Kingwede - Funzi Island",
                            new BigDecimal("-4.569388"), new BigDecimal("39.444261"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(66, "002/A", "Coral stone", "Kingwede - Funzi Island",
                            new BigDecimal("-4.571554"), new BigDecimal("39.442652"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(67, "002/A", "Murram", "Ramisi - Nyumba sita",
                            new BigDecimal("-4.452766"), new BigDecimal("39.489804"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(68, "002/A", "Coral Stone", "Kinondo - Makongeni",
                            new BigDecimal("-4.411372"), new BigDecimal("39.539732"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(69, "002/A", "Coral stone, Ballast, Quarry dust", "Kinondo - Makongeni",
                            new BigDecimal("-4.413087"), new BigDecimal("39.540274"), null, null, null, null, null, null, null, null, null),

                    // ========== KINANGO B1 DATA (Rows 70-91) ==========
                    new MaterialSite(70, "002/B1", "Local blocks, Kokoto", "Mwachanda",
                            new BigDecimal("-4.170327"), new BigDecimal("39.246377"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(71, "002/B1", "Slabs - local tiles", "Mwachanda",
                            new BigDecimal("-4.231178"), new BigDecimal("39.117298"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(72, "002/B1", "Slabs - local tiles, Hardcore blocks, Kokoto", "Gandini, South",
                            new BigDecimal("-4.291798"), new BigDecimal("39.1483"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(73, "002/B1", "Hardcore blocks", "Bomani, Katindani",
                            new BigDecimal("-4.249098"), new BigDecimal("39.160978"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(74, "002/B1", "Hardcore blocks, Small hardcore rocks", "Magulani",
                            new BigDecimal("-4.07713"), new BigDecimal("39.32258"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(75, "002/B1", "Hardcore blocks, Small hardcore rocks", "Magulani",
                            new BigDecimal("-4.0968"), new BigDecimal("39.31684"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(76, "002/B1", "Hardcore blocks, Small hardcore rocks", "Chonyi",
                            new BigDecimal("-4.108967"), new BigDecimal("39.292145"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(77, "002/B1", "Hardcore blocks, Small hardcore rocks", "Murungurunguni",
                            new BigDecimal("-4.112138"), new BigDecimal("39.263447"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(78, "002/B1", "Hardcore blocks, Small hardcore rocks", "Nyambu",
                            new BigDecimal("-4.111105"), new BigDecimal("39.257795"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(79, "002/B1", "Hardcore blocks, Small hardcore rocks, Kokoto, Galana", "Mwamandi",
                            new BigDecimal("-4.124355"), new BigDecimal("39.145853"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(80, "002/B1", "Hardcore blocks, Small hardcore rocks", "Makuluni",
                            new BigDecimal("-4.022363"), new BigDecimal("39.446792"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(81, "002/B1", "Hardcore blocks, Small hardcore rocks", "Vyogato",
                            new BigDecimal("-4.002562"), new BigDecimal("39.457288"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(82, "002/B1", "River Sand", "Mwache bridge",
                            new BigDecimal("-3.94485"), new BigDecimal("39.510227"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(83, "002/B1", "Ballast, Washed sand", "Bonje, Mwache",
                            new BigDecimal("-4.002532"), new BigDecimal("39.536543"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(84, "002/B1", "River Sand, Pit Sand", "Ngeyeni",
                            new BigDecimal("-3.941273"), new BigDecimal("39.416759"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(85, "002/B1", "River Sand, Pit Sand", "Maweu river",
                            new BigDecimal("-3.945935"), new BigDecimal("39.45409"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(86, "002/B1", "Ballast, Hardcore blocks, Maram", "Mdume, kafuduni",
                            new BigDecimal("-3.911902"), new BigDecimal("39.506902"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(87, "002/B1", "Hardcore Blocks, Hardcore rocks", "Mlola B",
                            new BigDecimal("-3.854295"), new BigDecimal("39.401202"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(88, "002/B1", "Hardcore blocks, Small hardcore rocks, Kokoto, Galana", "Julani",
                            new BigDecimal("-3.834985"), new BigDecimal("39.374405"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(89, "002/B1", "River Sand, Pit Sand, Hardcore blocks", "Lutsangami, Matumbi",
                            new BigDecimal("-3.925768"), new BigDecimal("39.392367"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(90, "002/B1", "River Sand, Pit Sand", "Vitsaka Viri",
                            new BigDecimal("-3.930928"), new BigDecimal("39.417397"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(91, "002/B1", "Ballast", "Mbandi",
                            new BigDecimal("-4.128325"), new BigDecimal("39.3289"), null, null, null, null, null, null, null, null, null),

                    // ========== KINANGO B2 DATA (Rows 92-108) ==========
                    new MaterialSite(92, "002/B2", "Stone blocks", "Mwachanda",
                            new BigDecimal("-4.21161"), new BigDecimal("39.177658"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(93, "002/B2", "Stone blocks", "Gandini South",
                            new BigDecimal("-4.3061583"), new BigDecimal("39.14797"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(94, "002/B2", "Concrete, Local tiles", "Tobora Village",
                            new BigDecimal("-4.28117"), new BigDecimal("39.150802"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(95, "002/B2", "Building blocks - stones", "Magulani",
                            new BigDecimal("-4.073624"), new BigDecimal("39.338492"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(96, "002/B2", "Stone blocks", "Mazola",
                            new BigDecimal("-4.102005"), new BigDecimal("39.302673"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(97, "002/B2", "Hardcore stone blocks", "Chonyi",
                            new BigDecimal("-4.101182"), new BigDecimal("39.278185"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(98, "002/B2", "Building blocks, Flooring stones", "Banga",
                            new BigDecimal("-4.107955"), new BigDecimal("39.26147"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(99, "002/B2", "Hardcore blocks, Galana Rainbow", "Mwamandi",
                            new BigDecimal("-4.124035"), new BigDecimal("39.143045"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(100, "002/B2", "Ballast, Chips, Quarry Dust", "Mwache",
                            new BigDecimal("-4.006463"), new BigDecimal("39.53152"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(101, "002/B2", "Pit sand", "Kibaoni",
                            new BigDecimal("-4.151222"), new BigDecimal("39.411458"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(102, "002/B2", "River sand", "Kirazini",
                            new BigDecimal("-4.147502"), new BigDecimal("39.306828"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(103, "002/B2", "Hardcore, Ballast, Builders blocks", "Mwache",
                            new BigDecimal("-3.95597"), new BigDecimal("39.512178"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(104, "002/B2", "Man Made Blocks", "Mafufuni",
                            new BigDecimal("-3.822524"), new BigDecimal("39.257677"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(105, "002/B2", "Galana, Hardcore stones", "Mwaruphesa",
                            null, null, null, null, null, null, null, null, null, null, null),
                    new MaterialSite(106, "002/B2", "Galana Slabs", "Deri",
                            new BigDecimal("-3.788378"), new BigDecimal("39.368875"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(107, "002/B2", "Galana Slabs, Hardcore", "Mwangoloto",
                            new BigDecimal("-3.742982"), new BigDecimal("39.359717"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(108, "002/B2", "Machine cut galana stones", "Mitangoni",
                            new BigDecimal("-3.792928"), new BigDecimal("39.389777"), null, null, null, null, null, null, null, null, null),

                    // ========== LUNGA LUNGA C1 DATA (Rows 109-118) ==========
                    new MaterialSite(109, "002/C1", "Hardcore stones, Pebbles", "Majengo mpya",
                            new BigDecimal("-4.547147"), new BigDecimal("39.12892"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(110, "002/C1", "River sand", "Mwalago",
                            new BigDecimal("-4.555745"), new BigDecimal("39.123745"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(111, "002/C1", "Mangroove", "Jimbo",
                            new BigDecimal("-4.664252"), new BigDecimal("39.210013"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(112, "002/C1", "Coral stone, Mangroove", "Vanga",
                            new BigDecimal("-4.659945"), new BigDecimal("39.21981"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(113, "002/C1", "River sand", "Dziriwe",
                            new BigDecimal("-4.592543"), new BigDecimal("39.168975"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(114, "002/C1", "Hardcore stones, Pebbles", "Mwalewa",
                            new BigDecimal("-4.56444"), new BigDecimal("39.143107"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(115, "002/C1", "Pebbles, Galana Stones", "Makwenyeni",
                            new BigDecimal("-4.5496"), new BigDecimal("39.089902"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(116, "002/C1", "Kasaurina Treg", "Kiwegu",
                            new BigDecimal("-4.611432"), new BigDecimal("39.19907"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(117, "002/C1", "Makuti", "Kiwegu",
                            new BigDecimal("-4.635763"), new BigDecimal("39.202447"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(118, "002/C1", "Murram Sand", "Tsuini",
                            new BigDecimal("-4.611067"), new BigDecimal("39.157185"), null, null, null, null, null, null, null, null, null),

                    // ========== LUNGA LUNGA C2 DATA (Rows 119-133) ==========
                    new MaterialSite(119, "002/C2", "Hardcore", "Masimbani",
                            new BigDecimal("-4.417948"), new BigDecimal("39.300033"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(120, "002/C2", "River Sand", "Eshu",
                            new BigDecimal("-4.421301"), new BigDecimal("39.340103"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(121, "002/C2", "Makuti", "Eshu",
                            new BigDecimal("-4.415973"), new BigDecimal("39.347973"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(122, "002/C2", "Pit/ Fine sand", "Mwangiwei",
                            new BigDecimal("-4.517318"), new BigDecimal("39.28149"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(123, "002/C2", "River Sand", "Perani",
                            new BigDecimal("-4.52089"), new BigDecimal("39.185235"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(124, "002/C2", "Hardcore", "Manda",
                            new BigDecimal("-4.497042"), new BigDecimal("39.19087"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(125, "002/C2", "Hand cut coral blocks", "Tswaka",
                            new BigDecimal("-4.611008"), new BigDecimal("39.358537"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(126, "002/C2", "Hardcore", "Twaka Firiri",
                            new BigDecimal("-4.600922"), new BigDecimal("39.364553"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(127, "002/C2", "Eucalyptus trees for roofing", "Godo A",
                            new BigDecimal("-4.531868"), new BigDecimal("39.037433"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(128, "002/C2", "Machine cut blocks", "Shimoni Wasini Village",
                            new BigDecimal("-4.656037"), new BigDecimal("39.361497"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(129, "002/C2", "Building Stone", "Mwagulu",
                            new BigDecimal("-4.390113"), new BigDecimal("39.123227"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(130, "002/C2", "Local building stone", "Makwenye",
                            new BigDecimal("-4.548752"), new BigDecimal("39.075335"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(131, "002/C2", "Bricks", "Sega D",
                            new BigDecimal("-4.551332"), new BigDecimal("39.122402"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(132, "002/C2", "Kashorina trees for roofing", "Mshiu",
                            new BigDecimal("-4.534582"), new BigDecimal("39.31285"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(133, "002/C2", "Timber from coconut trees", "Kidimu",
                            new BigDecimal("-4.542329"), new BigDecimal("39.366903"), null, null, null, null, null, null, null, null, null),

                    // ========== MATUGA DATA (Rows 134-153) ==========
                    new MaterialSite(134, "002/D", "Redish Murram", "Wayani",
                            new BigDecimal("-4.18382"), new BigDecimal("39.46456"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(135, "002/D", "Pit soil, Sand soil", "Ndagoni",
                            new BigDecimal("-4.16023"), new BigDecimal("39.44693"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(136, "002/D", "Natural stone", "Mwaguba",
                            new BigDecimal("-4.18822"), new BigDecimal("39.47944"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(137, "002/D", "Coarse Aggregates", "Lunguma",
                            new BigDecimal("-4.03326"), new BigDecimal("39.5849"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(138, "002/D", "Chips for block making", "Lunguma",
                            new BigDecimal("-4.03326"), new BigDecimal("39.5849"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(139, "002/D", "Hardcores", "Lunguma",
                            new BigDecimal("-4.03326"), new BigDecimal("39.5849"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(140, "002/D", "Machine cut blocks", "Kaya Waa",
                            new BigDecimal("-4.21736"), new BigDecimal("39.6078"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(141, "002/D", "Calcium Aggregates", "Kaya Waa",
                            new BigDecimal("-4.21736"), new BigDecimal("39.6078"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(142, "002/D", "Machine cut blocks", "Kwa Mtaliani",
                            new BigDecimal("-4.1219"), new BigDecimal("39.64"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(143, "002/D", "Bamboo trees", "Mwabuga",
                            new BigDecimal("-4.16909"), new BigDecimal("39.49368"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(144, "002/D", "Hardcore Dust", "Lunguma",
                            new BigDecimal("-4.03326"), new BigDecimal("39.5849"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(145, "002/D", "Coral Dust", "Kwa Mtaliani",
                            new BigDecimal("-4.1505"), new BigDecimal("39.6428"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(146, "002/D", "Calcium Chips", "Kaya Waa",
                            new BigDecimal("-4.17479"), new BigDecimal("39.59945"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(147, "002/D", "Vent's", "Kombani Stage",
                            new BigDecimal("-4.1748"), new BigDecimal("39.5995"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(148, "002/D", "Handcut blocks", "Kaya Waa",
                            new BigDecimal("-4.1748"), new BigDecimal("39.5995"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(149, "002/D", "Gololi - Pre cast concrete made structures", "Kombani Stage",
                            new BigDecimal("-4.1748"), new BigDecimal("39.5995"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(150, "002/D", "Timber", "Kombani Stage",
                            new BigDecimal("-4.1748"), new BigDecimal("39.5995"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(151, "002/D", "Calcium Hardcores", "Kwa mtaliani",
                            new BigDecimal("-4.1505"), new BigDecimal("39.6428"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(152, "002/D", "Natural stone", "Lunguma",
                            new BigDecimal("-4.0333"), new BigDecimal("39.5849"), null, null, null, null, null, null, null, null, null),
                    new MaterialSite(153, "002/D", "Pit Sand", "Subira",
                            new BigDecimal("-4.1705"), new BigDecimal("39.59"), null, null, null, null, null, null, null, null, null)
            );

            materialSiteService.saveAllMaterialSites(initialSites);
            System.out.println("Successfully loaded " + initialSites.size() + " material sites into database");
        } else {
            System.out.println("Material sites data already exists in database");
        }
    }
}
